# Generated by Django 5.2.6 on 2025-10-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='drawing',
            field=models.ImageField(blank=True, null=True, upload_to='note_drawings/'),
        ),
    ]
